# Generated by Django 5.2.1 on 2025-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='voter',
            old_name='registration_dt',
            new_name='date_of_registration',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='party',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='precinct',
        ),
        migrations.AddField(
            model_name='voter',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='street_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(default=0),
        ),
    ]
