# Generated by Django 5.2.1 on 2025-06-25 21:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toiletapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='restroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stall',
            options={'ordering': ['stall_no']},
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Special delivery instructions'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateTimeField(blank=True, help_text='Estimated delivery date/time', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('paper', 'Toilet Paper'), ('sanitizer', 'Hand Sanitizer'), ('soap', 'Hand Soap'), ('towels', 'Paper Towels'), ('other', 'Other Supplies')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restroom',
            name='has_baby_changing',
            field=models.BooleanField(default=False, help_text='Has baby changing station'),
        ),
        migrations.AddField(
            model_name='restroom',
            name='is_accessible',
            field=models.BooleanField(default=False, help_text='Wheelchair accessible'),
        ),
        migrations.AddField(
            model_name='restroom',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restroom',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for map display', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Review from verified visit'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stall',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated the status', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='default_delivery_address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_restrooms',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='toiletapp.restroom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='restroom',
            field=models.ForeignKey(help_text='Delivery location', on_delete=django.db.models.deletion.CASCADE, to='toiletapp.restroom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='restroom',
            name='avg_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='photo_urls',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='stall',
            name='stall_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('restroom', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='stall',
            unique_together={('restroom', 'stall_no')},
        ),
        migrations.AddIndex(
            model_name='restroom',
            index=models.Index(fields=['latitude', 'longitude'], name='toiletapp_r_latitud_bd242a_idx'),
        ),
        migrations.AddIndex(
            model_name='restroom',
            index=models.Index(fields=['avg_rating'], name='toiletapp_r_avg_rat_44f079_idx'),
        ),
    ]
